language: node_js

deploy:
  provider: heroku
  api_key:
    secure: "53711ff6-0487-4f5f-b742-544d89205040"
  

node_js: 
  - node

env:
  global:
    - CC_TEST_REPORTER_ID=bc96229170e06e65f474105f89e6367abf78482cba7b910b7af6a70d642697a5
    - SECRET_KEY=somethinglight

cache: 
  directories: 
    - "node_modules"    

rvm:
  - 2.2.0

services: 
  - postgresql  

before_script:
  - psql -c 'drop database if exists stackdb_test;' -U postgres
  - psql -c 'create database stackdb_test;' -U postgres
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm test

after_script:
  - npm run coverage
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
